name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./backend/* ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/531proj-api/

      - name: SSH into EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/531proj-api
            # Activate virtual environment, install dependencies, etc.
            source venv/bin/activate
            python3 -m pip install -r requirements.txt
            # Restart the application service (Gunicorn example)
            sudo systemctl restart 531proj-api
          EOF
